print('===== DESAFIO 02 =====')
print('Informe os dados a seguir:')
dia = input('Dia= ')
mes = input('Mês= ')
ano = input('Ano= ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, '. Correto?')
